version: 2
sources:
  - name: silver_raw
    database: "{{ 'SMARD_PROD' if target.name == 'prod' else 'SMARD_DEV' }}"
    schema: SILVER
    description: PySpark cleaned tables written to Snowflake Silver
    quoting:
      identifier: false
      column: true
    tables:
      - name: stg_energy_stream_clean
        description: PySpark cleaned real-time energy stream data
        loaded_at_field: 'TRY_TO_TIMESTAMP("_silver_processed_at")'
        freshness:
          warn_after:  {count: 1, period: hour}
          error_after: {count: 6, period: hour}
      - name: stg_energy_historical_clean
        description: PySpark cleaned historical energy data 2017-present
        loaded_at_field: 'TRY_TO_TIMESTAMP("_silver_processed_at")'
        freshness:
          warn_after:  {count: 2, period: day}
          error_after: {count: 7, period: day}
      - name: stg_weather_stream_clean
        description: PySpark cleaned real-time weather data
        loaded_at_field: 'TRY_TO_TIMESTAMP("_silver_processed_at")'
        freshness:
          warn_after:  {count: 1, period: hour}
          error_after: {count: 6, period: hour}
      - name: stg_weather_historical_clean
        description: PySpark cleaned historical weather data 2017-present
        loaded_at_field: 'TRY_TO_TIMESTAMP("_silver_processed_at")'
        freshness:
          warn_after:  {count: 2, period: day}
          error_after: {count: 7, period: day}
      - name: stg_cross_border_clean
        description: PySpark cleaned cross-border electricity flows Germany
        loaded_at_field: 'TRY_TO_TIMESTAMP("_silver_processed_at")'
        freshness:
          warn_after:  {count: 2, period: day}
          error_after: {count: 7, period: day}
